site_name: unified-io
site_description: "⚡️ A Blazing-Fast Python Library for Ranking Evaluation and Comparison 🐍"
site_url: "https://unified-io.github.io/"
repo_url: "https://github.com/amenra/unified-io"
edit_uri: "blob/master/docs/"
repo_name: "amenra/unified-io"
site_dir: "site"


theme:
  name: material
  palette: # 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 
      primary: red
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - unified_io

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true